user="root"
password="root"
bind="0.0.0.0"
port=3306
auth=false
#配置文件读取还是MysqlMP获取，可配置file、mp, 默认file也可以不配置
#mod="mp"
#server_url="http://192.168.0.47:8099/getrouteinfo"
#配置高可用用户验证id
#hook_id="WhHYnV1psD9Nyba3EbriIKuPPcTHnu6c"
#配置获取路由信息的集群名称
#cluster=["a"]

[[platform]]
#platform对应高可用cluster_name
platform="test1"
#业务通过set platform设置的名称
platform_sublist=["test1", "test2"]
write="192.168.1.126:3306"
#连接池建立使用的账号密码
user="root"
password="root"
min=10
max=100
auth=false

[[user]]
user_name="root"
#前端连接使用的密码,可以随意填写
password="root"
#对应platform模块中的platform_sublist
platform="test1"