user="root"
password="root"
bind="0.0.0.0"
port=3306
auth=false
#配置文件读取还是MysqlMP获取，可配置file、mp, 默认file也可以不配置
#mod="mp"
#server_url="http://192.168.0.47:8099/getrouteinfo"
#配置高可用用户验证id
#hook_id="WhHYnV1psD9Nyba3EbriIKuPPcTHnu6c"
#配置获取路由信息的集群名称
#cluster=["a"]

[[platform]]
platform="test1"
write="192.168.1.126:3306"
user="test"
password="test@123"
clipassword="test"
min=10
max=100
auth=false

#[[platform]]
#platform="test2"
#write="127.0.0.1:3309"
#read=["127.0.0.1:3309", "127.0.0.1:3310"]
#user="root"
#password="root"
#clipassword="root"
#min=10
#max=100
#auth=false